trigger:
  branches:
    include:
      - develop
      - main

jobs:
- job: BuildAndTest
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  - script: |
      pip install -r requirements.txt
      pip install pytest
      pytest tests/
    displayName: 'Install dependencies and run tests'
