version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///./db.sqlite3"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A tasks.celery_app worker --loglevel=info
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A tasks.celery_app beat --loglevel=info
    depends_on:
      - redis